{{ if or (and (index .Values "modules" "text2vec-openai" "enabled") (index .Values "modules" "text2vec-openai" "apiKey")) (and (index .Values "modules" "qna-openai" "enabled") (index .Values "modules" "qna-openai" "apiKey")) }}
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-openai
type: Opaque
data:
  {{- if (index .Values "modules" "qna-openai" "apiKey") }}
  apiKey: {{ index .Values "modules" "qna-openai" "apiKey" | b64enc }}
  {{- else }}
  apiKey: {{ index .Values "modules" "text2vec-openai" "apiKey" | b64enc }}
  {{- end }}
{{ end }}
