name: Main

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

jobs:
  create-helm-chart:
    name: Test and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: ./.cicd/test.sh
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: .cicd/release.sh
   
  create-draft-release:
    name: create draft release
    runs-on: ubuntu-latest
    needs: create-helm-chart
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844  # pin 3rd-party actions by commit 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: true
          files: weaviate/weaviate.tgz

  create-gh-page:
    name: create gh page
    runs-on: ubuntu-latest
    needs: create-helm-chart
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          # chartpress requires git history to set chart version and image tags
          # correctly
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.2

      - name: Install chart publishing dependencies (chartpress, helm)
        run: pip install chartpress
      
      - name: Run chart-releaser
        run: chartpress --publish-chart
